// Spanish translations — loaded on demand
(function(){if(window.translations)Object.assign(window.translations,{es:{
  documentTitle:'Daniel Ordonez Arango | Pentester',
  metaDescription:'Daniel Ordonez Arango — Penetration Tester con paths CPTS, CDSA, CJCA y CWEE completados. Seguridad web, redes y Active Directory. HTB Top 1%, 644 objetivos comprometidos.',
  ogTitle:'Daniel Ordonez Arango | Pentester',
  ogDescription:'Portafolio de seguridad ofensiva enfocado en penetration testing, analisis defensivo, calidad de reportes y superficies de ataque modernas.',
  selectors:{
    // ── Header ──
    '.brand-block .eyebrow':'Portafolio de Ciberseguridad',
    '.topnav a[href="#about"]':'Sobre mi',
    '.topnav a[href="#skills"]':'Habilidades',
    '.topnav a[href="#experience"]':'Experiencia',
    '.topnav a[href="#resources"]':'Recursos',
    '.topnav a[href="#certifications"]':'Certificaciones',
    '.topnav a[href="#contact"]':'Contacto',

    // ── Hero ──
    '.hero-copy .section-tag':'[ OPERADOR ACTIVO ]',
    '.hero-copy h2':'Pentester con experiencia en aplicaciones web, redes y sistemas.',
    '.hero-copy .lead':'Mi trabajo cubre el ciclo completo de reconocimiento, explotacion y elaboracion de informes claros orientados a quienes toman decisiones tecnicas y de negocio.',
    '.hero-copy .spec-item:nth-child(1) span':'Pentest Web',
    '.hero-copy .spec-item:nth-child(2) span':'Redes',
    '.hero-copy .spec-item:nth-child(3) span':'Active Directory',
    '.hero-copy .spec-item:nth-child(4) span':'SOC / DFIR',
    '.hero-copy .spec-item:nth-child(5) span':'IA / LLM',
    '.hero-actions .button.primary':'Contactame',
    '.hero-actions .button.secondary[href="daniel_cv_new.pdf"]':'Ver CV original',
    '.hero-actions .button.secondary[href="htb-academy-student-transcript.pdf"]':'Descargar transcript',
    '.quick-stats li:nth-child(1) span':'Paths HTB completados',
    '.quick-stats li:nth-child(2) span':'Objetivos comprometidos',
    '.quick-stats li:nth-child(3) span':'Ranking HTB',
    '.link-strip a[href="https://www.linkedin.com/in/danie125/"]':'LinkedIn',
    '.link-strip a[href="https://github.com/dan1e124"]':'GitHub',
    '.avail-text':'Disponible para proyectos',

    // ── Terminal ──
    '.terminal-label':'daniel@portfolio:~$ ./escaneo_perfil',
    '.status-grid div:nth-child(1) span':'Estado',
    '.status-grid div:nth-child(1) strong':'ACTIVO',
    '.status-grid div:nth-child(2) span':'Enfoque',
    '.status-grid div:nth-child(2) strong':'PENTEST',
    '.status-grid div:nth-child(3) span':'Cobertura',
    '.status-grid div:nth-child(3) strong':'WEB / RED / SYS',
    '.status-grid div:nth-child(4) span':'Evidencia',
    '.status-grid div:nth-child(4) strong':'WEB / RED / SIS','.status-grid div:nth-child(5) span':'Disponibilidad','.status-grid div:nth-child(5) strong':'ABIERTO','.status-grid div:nth-child(6) span':'Idiomas','.status-grid div:nth-child(6) strong':'ES / EN',

    // ── Experience ──
    '#experience .section-heading .section-tag':'[ EXPERIENCIA ]',
    '#experience .section-heading h3':'Impacto Real y Trayectoria Profesional',
    '#experience > h4:nth-of-type(1)':'Por que destaca este perfil',
    '#experience .mini-grid--mb .mini-card:nth-child(1) strong':'Contexto Ofensivo + Defensivo',
    '#experience .mini-grid--mb .mini-card:nth-child(1) span':'Evaluo debilidades con mentalidad de atacante manteniendo el foco en remediacion y prioridades defensivas.',
    '#experience .mini-grid--mb .mini-card:nth-child(2) strong':'Vision de Aplicacion + Infraestructura',
    '#experience .mini-grid--mb .mini-card:nth-child(2) span':'Trabajo en aplicaciones web, redes internas, servidores y bases de datos, proporcionando cobertura de seguridad integral.',
    '#experience .mini-grid--mb .mini-card:nth-child(3) strong':'Entrenamiento en Respuesta a Incidentes',
    '#experience .mini-grid--mb .mini-card:nth-child(3) span':'Entrenado en DFIR a traves del path CDSA — triaje de amenazas, analisis forense y contencion de incidentes.',
    '#experience .mini-grid--mb .mini-card:nth-child(4) strong':'Conocimiento de Desarrollador',
    '#experience .mini-grid--mb .mini-card:nth-child(4) span':'Mi experiencia en desarrollo conecta vulnerabilidades con realidades de implementacion, haciendo la remediacion mas practica.',
    '#experience > h4:nth-of-type(2)':'Historial operativo',
    '#experience .timeline-item:nth-child(1) .role':'Desarrollador Full-Stack y Especialista en Seguridad · Dic 2025 – Presente',
    '#experience .timeline-item:nth-child(1) .detail-list li:nth-child(1)':'Metodologia completa de pentesting cubriendo web, redes y Active Directory a traves del path CPTS.',
    '#experience .timeline-item:nth-child(1) .detail-list li:nth-child(2)':'Entrenamiento en reportes profesionales — traduciendo hallazgos tecnicos en impacto de negocio accionable.',
    '#experience .timeline-item:nth-child(1) .detail-list li:nth-child(3)':'Tecnicas avanzadas de explotacion web incluyendo cadenas de ataque CWEE server-side y client-side, no solo del descubrimiento.',
    '#experience .timeline-item:nth-child(2) .role':'Entrenamiento en Seguridad Ofensiva · 2025',
    '#experience .timeline-item:nth-child(2) .detail-list li:nth-child(1)':'Completado el path CPTS — metodologia completa de pentesting para web, redes y Active Directory.',
    '#experience .timeline-item:nth-child(2) .detail-list li:nth-child(2)':'Tecnicas avanzadas de explotacion web del lado del servidor y del cliente a traves del path CWEE.',
    '#experience .timeline-item:nth-child(2) .detail-list li:nth-child(3)':'Entrenamiento en reporting profesional — traducir hallazgos tecnicos en impacto de negocio accionable.',
    '#experience .timeline-item:nth-child(3) .role':'Entrenamiento en Seguridad Defensiva · 2025',
    '#experience .timeline-item:nth-child(3) .detail-list li:nth-child(1)':'Entrenamiento en monitoreo SIEM y analisis de logs usando Splunk y Elastic Stack.',
    '#experience .timeline-item:nth-child(3) .detail-list li:nth-child(2)':'Labs de DFIR y respuesta a incidentes, incluyendo adquisicion forense y triaje de amenazas.',
    '#experience .timeline-item:nth-child(3) .detail-list li:nth-child(3)':'Construccion de reglas de deteccion con Suricata/Snort y desarrollo de playbooks de respuesta a incidentes.',

    // ── Skills ──
    '#skills article:nth-child(1) .section-tag':'[ ARSENAL TECNICO ]',
    '#skills article:nth-child(1) h4':'Herramientas de Pentesting',
    '#skills article:nth-child(2) div:nth-child(1) h4':'Programacion y Scripting',
    '#skills article:nth-child(2) div:nth-child(2) h4':'Infraestructura y Plataformas',
    '#skills article:nth-child(2) div:nth-child(3) h4':'Compliance y Metodologias',

    // ── HTB Lab Coverage ──
    '#htb-coverage .section-tag':'[ 658 OBJETIVOS COMPROMETIDOS ]',
    '#htb-coverage h3':'Cobertura de Laboratorios HackTheBox',
    '#htb-coverage .section-copy':'658 objetivos comprometidos en 12 paths completados — cubriendo pentesting web, redes, analisis SOC, escalacion de privilegios y explotacion binaria.',
    '#htb-coverage .mini-grid:nth-child(2) .mini-card:nth-child(1) strong':'Explotacion de Aplicaciones Web',
    '#htb-coverage .mini-grid:nth-child(2) .mini-card:nth-child(1) span':'Inyeccion SQL, XSS, CSRF, SSRF, bypasses de carga de archivos, fallas de autenticacion, vulnerabilidades de API, deserializacion insegura, XXE, control de acceso roto, IDOR e inyeccion de comandos. Cubierto en los paths CPTS y Web Penetration Tester.',
    '#htb-coverage .mini-grid:nth-child(2) .mini-card:nth-child(2) strong':'Ataques Active Directory',
    '#htb-coverage .mini-grid:nth-child(2) .mini-card:nth-child(2) span':'Kerberoasting, AS-REP roasting, DCSync, Pass-the-Hash, Pass-the-Ticket, abuso de GPO, explotacion de ACL, enumeracion con BloodHound, escalacion de privilegios de dominio y tecnicas de persistencia. Cubierto en el path Penetration Tester.',
    '#htb-coverage .mini-grid:nth-child(2) .mini-card:nth-child(3) strong':'Escalacion de Privilegios',
    '#htb-coverage .mini-grid:nth-child(2) .mini-card:nth-child(3) span':'Linux: binarios SUID/SGID, exploits de kernel, configuraciones incorrectas de sudo, abuso de cron jobs, rutas con escritura y shares NFS. Windows: SeImpersonatePrivilege, rutas de servicio sin comillas, DLL hijacking, manipulacion de registro e impersonacion de tokens.',
    '#htb-coverage .mini-grid:nth-child(2) .mini-card:nth-child(4) strong':'Explotacion de Red y Servicios',
    '#htb-coverage .mini-grid:nth-child(2) .mini-card:nth-child(4) span':'Explotacion de SMB, RDP, SSH, FTP, SNMP, WinRM y MSSQL. Port forwarding, proxychains, pivoting a traves de hosts comprometidos, tunneling y movimiento lateral en redes segmentadas.',
    '#htb-coverage .mini-grid:nth-child(3) .mini-card:nth-child(1) strong':'Reconocimiento y Enumeracion',
    '#htb-coverage .mini-grid:nth-child(3) .mini-card:nth-child(1) span':'Reconocimiento pasivo y activo usando Nmap, Masscan, Gobuster, ffuf, Wfuzz, Feroxbuster, Shodan y tecnicas OSINT. Enumeracion DNS, descubrimiento de subdominios, fuzzing de virtual hosts y consultas de transparencia de certificados.',
    '#htb-coverage .mini-grid:nth-child(3) .mini-card:nth-child(2) strong':'Analisis SOC y Deteccion de Amenazas',
    '#htb-coverage .mini-grid:nth-child(3) .mini-card:nth-child(2) span':'Analisis de logs, monitoreo SIEM con Splunk y Elastic Stack, analisis de trafico con Wireshark y tcpdump, ajuste de reglas IDS/IPS con Suricata y Snort. Actividades DFIR, threat hunting y triaje de incidentes. Cubierto en los paths CDSA y SOC Analyst.',
    '#htb-coverage .mini-grid:nth-child(3) .mini-card:nth-child(3) strong':'Explotacion de Binarios',
    '#htb-coverage .mini-grid:nth-child(3) .mini-card:nth-child(3) span':'Ataques de buffer overflow en sistemas Windows y Linux de 32 bits, analisis de arquitectura CPU y registros, desarrollo de shellcode, scripting de exploits en Python y tecnicas de overflow basadas en pila. Cubierto en el path Intro to Binary Exploitation.',
    '#htb-coverage .mini-grid:nth-child(3) .mini-card:nth-child(4) strong':'Post-Explotacion y Persistencia',
    '#htb-coverage .mini-grid:nth-child(3) .mini-card:nth-child(4) span':'Volcado de credenciales con Mimikatz y secretsdump, conceptos de staging C2, mantenimiento de acceso via tareas programadas y run keys de registro, tecnicas de exfiltracion de datos y borrado de huellas en entornos Windows y Linux.',
    '#htb-coverage .mini-grid:nth-child(4) .mini-card:nth-child(1) strong':'Red Teaming IA / LLM',
    '#htb-coverage .mini-grid:nth-child(4) .mini-card:nth-child(1) span':'Ataques de prompt injection, ML adversarial, manipulacion de salidas LLM, explotacion de pipelines de IA, evasion de modelos (caja blanca y negra), vulnerabilidades del protocolo MCP y ataques a aplicaciones de IA.',
    '#htb-coverage .mini-grid:nth-child(4) .mini-card:nth-child(2) strong':'Pentesting Wi-Fi',
    '#htb-coverage .mini-grid:nth-child(4) .mini-card:nth-child(2) span':'Captura de handshakes WPA/WPA2, ataques PMKID, puntos de acceso evil twin, ataques de deautenticacion, explotacion WPS, cracking con Hashcat y Aircrack-ng y estrategias de diccionario para evaluaciones inalambricas.',
    '#htb-coverage .mini-grid:nth-child(4) .mini-card:nth-child(3) strong':'Analisis de Malware y DFIR',
    '#htb-coverage .mini-grid:nth-child(4) .mini-card:nth-child(3) span':'Analisis estatico y dinamico de malware, desempaquetado, ingenieria inversa con x64dbg, forense de memoria con Volatility, imagenes de disco con FTK Imager y KAPE, forense Linux y reconstruccion de linea de tiempo desde MFT/USN Journal.',
    '#htb-coverage .mini-grid:nth-child(4) .mini-card:nth-child(4) strong':'Hardening de Active Directory',
    '#htb-coverage .mini-grid:nth-child(4) .mini-card:nth-child(4) span':'Remediacion de hallazgos comunes de pentest en AD, hardening de configuraciones por defecto, ingenieria de deteccion, estrategias de logging y buenas practicas de mantenimiento. Cubre perspectivas del atacante y del defensor.',
    '#htb-coverage .mini-grid:nth-child(4) .mini-card:nth-child(1) strong':'Red Teaming IA / LLM',
    '#htb-coverage .mini-grid:nth-child(4) .mini-card:nth-child(1) span':'Ataques de prompt injection, ML adversarial, manipulacion de salidas LLM, explotacion de pipelines de datos IA, evasion de modelos (caja blanca y negra), vulnerabilidades del protocolo MCP y ataques a aplicaciones de IA.',
    '#htb-coverage .mini-grid:nth-child(4) .mini-card:nth-child(2) strong':'Pentesting Wi-Fi',
    '#htb-coverage .mini-grid:nth-child(4) .mini-card:nth-child(2) span':'Captura de handshakes WPA/WPA2, ataques PMKID, puntos de acceso evil twin, ataques de deautenticacion, explotacion de WPS, crackeo de contrasenas con Hashcat y Aircrack-ng, y estrategias de diccionario para evaluaciones inalambricas.',
    '#htb-coverage .mini-grid:nth-child(4) .mini-card:nth-child(3) strong':'Analisis de Malware y DFIR',
    '#htb-coverage .mini-grid:nth-child(4) .mini-card:nth-child(3) span':'Analisis estatico y dinamico de malware, desempaquetado, ingenieria inversa con x64dbg, forense de memoria con Volatility, imagenes de disco con FTK Imager y KAPE, forense en Linux, reconstruccion de linea de tiempo desde MFT/USN Journal y registros de eventos de Windows.',
    '#htb-coverage .mini-grid:nth-child(4) .mini-card:nth-child(4) strong':'Hardening de Active Directory',
    '#htb-coverage .mini-grid:nth-child(4) .mini-card:nth-child(4) span':'Remediacion de hallazgos comunes de pentest en AD, hardening de configuraciones por defecto, ingenieria de deteccion para ataques AD, estrategias de logging y mejores practicas de mantenimiento. Cubre perspectivas tanto de atacante como de defensor.',

    // ── Certifications ──
    '#certifications article:nth-child(1) .section-tag':'[ EDUCACION / CERTIFICACIONES ]',
    '#certifications .training-section:nth-of-type(1) .section-tag':'[ Paths HTB de Job Role y Skills Completados ]',
    '#certifications article:nth-child(1) h3':'Base de formacion',
    '#certifications article:nth-child(1) .section-copy':'Certificaciones externas y fundamentos de desarrollo que complementan el entrenamiento en HTB Academy.',
    '#certifications .training-section:nth-of-type(1) .subsection-label':'Paths de certificacion HTB — entrenamiento completado, examen pendiente',
    '.path-card:nth-child(1) span:last-child':'Reconocimiento web, explotacion, APIs y reporting profesional.',
    '.path-card:nth-child(2) span:last-child':'Metodologia, evaluaciones enterprise, explotacion y reporting.',
    '.path-card:nth-child(3) span:last-child':'Monitoreo, SIEM, analisis de trafico, DFIR y reporting.',
    '.path-card:nth-child(4) span:last-child':'Fundamentos ofensivos y defensivos para trabajo practico en ciberseguridad.',
    '.path-card:nth-child(5) strong':'Enumeracion de Active Directory',
    '.path-card:nth-child(5) span:last-child':'Tecnicas de enumeracion de Active Directory en profundidad, herramientas y mapeo de superficie de ataque. Path de alta dificultad.',
    '.path-card:nth-child(6) strong':'Fundamentos de Seguridad de la Informacion',
    '.path-card:nth-child(6) span:last-child':'Conceptos esenciales de InfoSec: redes, criptografia, metodologia de pentesting y fundamentos de carrera.',
    '.path-card:nth-child(7) strong':'Prerrequisitos de Analista SOC',
    '.path-card:nth-child(7) span:last-child':'Conocimiento previo para operaciones SOC — fundamentos de seguridad y conceptos de analisis de amenazas.',
    '.path-card:nth-child(8) strong':'Fundamentos de Sistemas Operativos',
    '.path-card:nth-child(8) span:last-child':'Internos de Windows y Linux, administracion y hardening alineados con las mejores practicas de seguridad.',
    '.path-card:nth-child(9) strong':'Escalacion de Privilegios Local',
    '.path-card:nth-child(9) span:last-child':'Tecnicas de escalacion de privilegios manuales y asistidas por herramientas en sistemas Windows y Linux.',
    '.path-card:nth-child(10) strong':'Introduccion a la Explotacion de Binarios',
    '.path-card:nth-child(10) span:last-child':'Buffer overflows, shellcode y scripting de exploits. Path de alta dificultad.',
    '.path-card:nth-child(11) strong':'Arsenal Basico de Herramientas',
    '.path-card:nth-child(11) span:last-child':'Herramientas fundamentales de seguridad ofensiva y su aplicacion practica en distintos escenarios.',
    '.path-card:nth-child(12) strong':'Comenzando en Hack The Box',
    '.path-card:nth-child(12) span:last-child':'Primera maquina HTB guiada — conectando el conocimiento de la academia con labs del mundo real.',
    '.cert-group:nth-child(1) .subsection-label':'Estudios externos de ciberseguridad',
    '.cert-pill-group .section-tag':'[ IDIOMAS ]',
    '.cert-pill-group .pill-grid span:nth-child(1)':'Ingles',
    '.cert-pill-group .pill-grid span:nth-child(2)':'Espanol',

    // ── About ──
    '#about article:nth-child(1) .section-tag':'[ SOBRE MI ]',
    '#about article:nth-child(1) h3':'Resumen profesional',

    // ── Resources ──
    '#resources article:nth-child(1) .section-tag':'[ RECURSOS ]',
    '#resources article:nth-child(1) h3':'Material descargable',
    '#resources article:nth-child(1) .section-copy':'Todas las afirmaciones en esta página están respaldadas por credenciales verificables. Descarga la transcripción o consulta el perfil de HTB directamente.',
    '.transcript-featured strong':'Transcript de HTB Academy',
    '.evidence-badge':'★ Evidencia Principal',
    '.transcript-featured > span':'El transcript oficial de Hack The Box Academy documenta 11 paths de roles completados, 644 objetivos comprometidos, ranking Top 1% y paths CPTS, CDSA, CJCA y CWEE completados — evidencia principal que respalda cada afirmacion de este portafolio.',
    '.transcript-mini-stats div:nth-child(1) span':'objetivos',
    '.transcript-mini-stats div:nth-child(2) span':'paths',
    '.transcript-mini-stats div:nth-child(3) span':'ranking',
    '.transcript-mini-stats div:nth-child(4) span':'certificaciones',
    '.transcript-download-btn':'↓ Descargar Transcript',
    '.student-id-badge':'ID: HTB-E9139F3DCE',
    '.htb-verify-link strong':'Verificar en HTB Academy',
    '.htb-verify-link .verify-body span':'Ingresa el ID HTB-E9139F3DCE en hackthebox.com/certificates para verificar credenciales',

    // ── Contact ──
    '#contact .section-tag':'[ CONTACTO Y REDES ]',
    '#contact h3':'Canal seguro',
    '.contact-intro':'Si necesitas un penetration tester que comunique hallazgos con claridad, contactame por cualquiera de los siguientes canales.',
    '.contact-card-email-title':'Correo',
    '.contact-card-email-copy':'Canal de mensaje directo',
    '.contact-card-phone-title':'Telefono',
    '.contact-card-phone-copy':'Canal de llamada',
    '#contact .social-grid .social-link:nth-child(3) .social-copy strong':'LinkedIn',
    '#contact .social-grid .social-link:nth-child(3) .social-copy span':'Perfil profesional y networking',
    '#contact .social-grid .social-link:nth-child(4) .social-copy strong':'GitHub',
    '#contact .social-grid .social-link:nth-child(4) .social-copy span':'Codigo, proyectos y huella tecnica',

    // ── Footer ──
    'footer a[href="#main"]':'↑ Volver arriba',
    '.contact-form-card .section-tag':'[ ENVIAR MENSAJE ]',
    '.cf-heading':'Mensaje directo',
    'label[for="cf-name"]':'Nombre',
    'label[for="cf-email"]':'Correo',
    'label[for="cf-message"]':'Mensaje',
    '.cf-btn-text':'Enviar mensaje'
  },
  placeholders:{
    '#cf-name':'Tu nombre',
    '#cf-email':'tu@correo.com',
    '#cf-message':'Describe el proyecto o engagement...'
  },
  terminalLines:[
    '> Enumerando modulos de experiencia...','> Paths HTB completados: 11','> Objetivos comprometidos: 644','> Ranking: Top 1%','> Enfoque: seguridad web, de red y enterprise','> Objetivo: reducir riesgo explotable'
  ]
}});})();
