/* Generated by scripts/build.mjs � do not edit */
window.SITE_CONFIG = {
  "version": "20260715-f4495d3",
  "name": "Daniel Ordonez Arango",
  "url": "https://danieloa.com",
  "email": "danielordonezarango@gmail.com",
  "phone": "+573136459299",
  "whatsapp": "573136459299",
  "gaId": "G-1VX6JE5WXW",
  "formspree": "https://formspree.io/f/xpqykjpa",
  "links": {
    "linkedin": "https://www.linkedin.com/in/danielordonezarango",
    "github": "https://github.com/dan1e125",
    "htb": "https://profile.hackthebox.com/profile/019d0d58-909e-7011-97e3-1f8ebc6567af",
    "calendly": "https://calendly.com/danielordonezarango/30min"
  },
  "stats": {
    "targets": 720,
    "paths": 12,
    "ranking": "Top 1%",
    "modules": 105
  },
  "pricing": {
    "webFrom": 2000,
    "adFrom": 3000,
    "priceRange": "$2,000 - $7,000"
  }
};
