import {
  readFileSync,
  writeFileSync,
  readdirSync,
  existsSync,
  mkdirSync,
} from 'node:fs';
import { execSync } from 'node:child_process';
import { join, dirname } from 'node:path';
import { pathToFileURL } from 'node:url';
import { fileURLToPath } from 'node:url';
import { SITE } from './site.config.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');

function read(file) {
  return readFileSync(join(ROOT, file), 'utf8');
}

function write(file, content) {
  writeFileSync(join(ROOT, file), content, 'utf8');
}

function escapeHtml(value) {
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function escapeJs(value) {
  return String(value)
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\n/g, '\\n');
}

function replaceBlock(content, start, end, replacement) {
  const s = content.indexOf(start);
  const e = content.indexOf(end);
  if (s === -1 || e === -1) throw new Error(`Missing markers: ${start}`);
  return content.slice(0, s + start.length) + '\n' + replacement + '\n' + content.slice(e);
}

function bumpAssetVersion(content, version) {
  return content.replace(/\?v=[^"'\s]+/g, `?v=${version}`);
}

function faqSchemaScript(faqEn) {
  const mainEntity = faqEn.map((item) => ({
    '@type': 'Question',
    name: item.q,
    acceptedAnswer: { '@type': 'Answer', text: item.a },
  }));
  return `<script type="application/ld+json">\n${JSON.stringify(
    { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity },
    null,
    2
  )}\n</script>`;
}

function faqItemsJs(items) {
  return items
    .map(
      (item) =>
        `      {\n        q: '${escapeJs(item.q)}',\n        a: '${escapeJs(item.a)}'\n      }`
    )
    .join(',\n');
}

function buildSiteConfig(version) {
  const payload = {
    version,
    name: SITE.name,
    url: SITE.url,
    email: SITE.email,
    phone: SITE.phone,
    whatsapp: SITE.whatsapp,
    gaId: SITE.gaId,
    formspree: SITE.formspree,
    links: SITE.links,
    stats: SITE.stats,
    pricing: SITE.pricing,
  };
  return `/* Generated by scripts/build.mjs — do not edit */\nwindow.SITE_CONFIG = ${JSON.stringify(payload, null, 2)};\n`;
}

function buildLlmsTxt(caseFiles) {
  const { url, email, links, stats, pricing } = SITE;
  const caseLines = caseFiles
    .map((c) => {
      const pageUrl = `${url}/case-studies/${c.slug}.html`;
      return `- [Case Study: ${c.breadcrumbTitle}](${pageUrl}): ${c.en.metaDescription}`;
    })
    .join('\n');

  return `# ${SITE.name}

> Freelance penetration tester based in Colombia. Specializes in web application security and Active Directory attacks. Available for remote engagements worldwide in English and Spanish.

${SITE.name} is a cybersecurity professional focused on offensive security. HTB Academy: ${stats.paths} paths completed, ${stats.targets} lab targets compromised, ${stats.modules} modules completed, ${stats.ranking} ranking.

Contact: ${email}

## Services
- Web Application Penetration Testing: OWASP Top 10, business logic, API security. From $${pricing.webFrom.toLocaleString('en-US')} USD.
- Active Directory Penetration Testing: Kerberoasting, lateral movement, privilege escalation. From $${pricing.adFrom.toLocaleString('en-US')} USD.

## Key Facts
- Based in Colombia, works remotely worldwide
- Fluent in English and Spanish
- Portfolio: ${url}

## Links
- [Portfolio](${url}): Full portfolio with case studies, services, and contact form
- [HTB Academy Transcript (PDF)](${url}/htb-academy-student-transcript.pdf): Official student transcript
${caseLines}
- [LinkedIn](${links.linkedin}): Professional profile
- [GitHub](${links.github}): Code repositories
- [Hack The Box](${links.htb}): HTB profile
`;
}

function buildSitemap(caseFiles, lastmod) {
  const urls = [
    { loc: `${SITE.url}/`, priority: '1.0', changefreq: 'monthly', hreflang: true },
    ...caseFiles.map((c) => ({
      loc: `${SITE.url}/case-studies/${c.slug}.html`,
      priority: '0.8',
      changefreq: 'yearly',
      hreflang: false,
    })),
  ];

  const body = urls
    .map((u) => {
      const hreflang = u.hreflang
        ? `\n    <xhtml:link rel="alternate" hreflang="en" href="${u.loc}"/>\n    <xhtml:link rel="alternate" hreflang="es" href="${u.loc}"/>\n    <xhtml:link rel="alternate" hreflang="x-default" href="${u.loc}"/>`
        : '';
      return `  <url>\n    <loc>${u.loc}</loc>\n    <lastmod>${lastmod}</lastmod>\n    <changefreq>${u.changefreq}</changefreq>\n    <priority>${u.priority}</priority>${hreflang}\n  </url>`;
    })
    .join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"\n        xmlns:xhtml="http://www.w3.org/1999/xhtml">\n${body}\n</urlset>\n`;
}

function buildCaseI18n(caseFiles) {
  const toPage = (lang, data) => {
    const selectors = {
      '#case-back': data.back,
      '#case-tag': data.tag,
      '#case-title': data.title,
      '#case-h2-summary': data.headings.summary,
      '#case-h2-findings': data.headings.findings,
      '#case-h2-methodology': data.headings.methodology,
      '#case-h2-outcome': data.headings.outcome,
      '#case-p-summary': data.summary,
      '#case-p-methodology': data.methodology,
      '#case-p-outcome': data.outcome,
    };
    const htmlSelectors = {
      '#case-meta-client': `<strong>${lang === 'es' ? 'Cliente' : 'Client'}:</strong> ${data.meta.client}`,
      '#case-meta-service': `<strong>${lang === 'es' ? 'Servicio' : 'Service'}:</strong> ${data.meta.service}`,
      '#case-meta-type': `<strong>${lang === 'es' ? 'Tipo' : 'Type'}:</strong> ${data.meta.type}`,
    };
    data.findings.forEach((finding, i) => {
      if (finding) htmlSelectors[`#case-finding-${i + 1}`] = finding;
    });
    return {
      documentTitle: data.documentTitle,
      metaDescription: data.metaDescription,
      selectors,
      htmlSelectors,
    };
  };

  const en = {};
  const es = {};
  for (const c of caseFiles) {
    en[c.slug] = toPage('en', c.en);
    es[c.slug] = toPage('es', c.es);
  }

  return `(function () {
  'use strict';

  var STORAGE_KEY = 'portfolio-lang';

  var COPY = {
    en: ${JSON.stringify(en, null, 4).replace(/^/gm, '    ')},
    es: ${JSON.stringify(es, null, 4).replace(/^/gm, '    ')}
  };

  function pageSlug() {
    var slug = document.body && document.body.getAttribute('data-case-slug');
    if (slug) return slug;
    var match = location.pathname.match(/\\/case-studies\\/([^/]+)\\.html$/);
    return match ? match[1] : null;
  }

  function getLocale() {
    var stored = localStorage.getItem(STORAGE_KEY);
    return stored === 'es' ? 'es' : 'en';
  }

  function applySelectors(map, useHtml) {
    if (!map) return;
    Object.keys(map).forEach(function (selector) {
      var node = document.querySelector(selector);
      if (!node) return;
      if (useHtml) node.innerHTML = map[selector];
      else node.textContent = map[selector];
    });
  }

  function applyLocale(locale) {
    var slug = pageSlug();
    if (!slug) return;
    var page = COPY[locale] && COPY[locale][slug];
    if (!page) return;

    document.documentElement.lang = locale === 'es' ? 'es' : 'en';
    if (page.documentTitle) document.title = page.documentTitle;
    var meta = document.querySelector('meta[name="description"]');
    if (meta && page.metaDescription) meta.setAttribute('content', page.metaDescription);

    applySelectors(page.selectors, false);
    applySelectors(page.htmlSelectors, true);

    document.querySelectorAll('[data-case-lang]').forEach(function (btn) {
      var active = btn.getAttribute('data-case-lang') === locale;
      btn.classList.toggle('is-active', active);
      btn.setAttribute('aria-pressed', active ? 'true' : 'false');
    });

    localStorage.setItem(STORAGE_KEY, locale);
  }

  function initLangSwitch() {
    document.querySelectorAll('[data-case-lang]').forEach(function (btn) {
      btn.addEventListener('click', function () {
        applyLocale(btn.getAttribute('data-case-lang') || 'en');
      });
    });
  }

  applyLocale(getLocale());
  initLangSwitch();
})();
`;
}

function buildCaseStudyHtml(caseData, template, version, lastmod) {
  const en = caseData.en;
  const canonical = `${SITE.url}/case-studies/${caseData.slug}.html`;
  const findingsHtml = en.findings
    .filter(Boolean)
    .map((f, i) => `          <li id="case-finding-${i + 1}">${f}</li>`)
    .join('\n');

  const articleSchema = JSON.stringify({
    '@context': 'https://schema.org',
    '@type': 'Article',
    headline: caseData.articleHeadline,
    description: caseData.articleDescription,
    author: { '@type': 'Person', name: SITE.name, url: SITE.url },
    datePublished: caseData.datePublished,
    dateModified: lastmod,
    url: canonical,
    publisher: { '@type': 'Person', name: SITE.name, url: SITE.url },
  });

  const breadcrumbSchema = JSON.stringify({
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: 'Home', item: `${SITE.url}/` },
      { '@type': 'ListItem', position: 2, name: 'Case Studies', item: `${SITE.url}/#case-studies` },
      { '@type': 'ListItem', position: 3, name: caseData.breadcrumbTitle, item: canonical },
    ],
  });

  const vars = {
    slug: caseData.slug,
    authorName: SITE.name,
    canonicalUrl: canonical,
    ogTitle: escapeHtml(caseData.ogTitle),
    metaDescription: escapeHtml(en.metaDescription),
    ogImage: `${SITE.url}/og-image.png`,
    ogImageAlt: `${SITE.name} — Penetration Tester portfolio`,
    twitterTitle: escapeHtml(caseData.twitterTitle),
    twitterDescription: escapeHtml(caseData.twitterDescription),
    assetVersion: version,
    articleSchema,
    breadcrumbSchema,
    tag: escapeHtml(en.tag),
    title: escapeHtml(en.title),
    metaClient: escapeHtml(en.meta.client),
    metaService: escapeHtml(en.meta.service),
    metaType: escapeHtml(en.meta.type),
    headingSummary: escapeHtml(en.headings.summary),
    headingFindings: escapeHtml(en.headings.findings),
    headingMethodology: escapeHtml(en.headings.methodology),
    headingOutcome: escapeHtml(en.headings.outcome),
    summary: escapeHtml(en.summary),
    methodology: escapeHtml(en.methodology),
    outcome: escapeHtml(en.outcome),
    findingsHtml,
  };

  return template.replace(/\{\{(\w+)\}\}/g, (_, key) => vars[key] ?? '');
}

function patchIndexHtml(index, faqEn, version, lastmod) {
  let html = index;
  html = replaceBlock(
    html,
    '<!-- @build:faq-schema-script -->',
    '<!-- @end:faq-schema-script -->',
    faqSchemaScript(faqEn)
  );
  html = html.replace(/"dateModified": "[^"]+"/, `"dateModified": "${lastmod}"`);
  html = html.replace(
    /"sameAs": \[[\s\S]*?\]/,
    `"sameAs": [\n        "${SITE.links.linkedin}",\n        "${SITE.links.github}",\n        "${SITE.links.htb}"\n      ]`
  );
  html = html.replace(/"email": "danielordonezarango@gmail.com"/g, `"email": "${SITE.email}"`);
  html = html.replace(/"telephone": "\+573136459299"/g, `"telephone": "${SITE.phone}"`);
  html = html.replace(/"priceRange": "\$2,000 - \$7,000"/g, `"priceRange": "${SITE.pricing.priceRange}"`);
  html = html.replace(/gtag\('config', '[^']+'/g, `gtag('config', '${SITE.gaId}'`);
  html = html.replace(/content="a7f3d9e2c1b84650f892a3d7c5e1f094"/g, `content="${SITE.indexNowKey}"`);
  html = html.replace(/src="site-config\.js\?v=[^"]+"/, `src="site-config.js?v=${version}"`);
  return bumpAssetVersion(html, version);
}

function patchTranslations(translations, faq) {
  let js = translations;
  js = replaceBlock(js, '    // @build:faq-en-items', '    // @end:faq-en-items', faqItemsJs(faq.en));
  js = replaceBlock(js, '    // @build:faq-es-items', '    // @end:faq-es-items', faqItemsJs(faq.es));
  return js;
}

function buildSw(version) {
  let sw = read('sw.js');
  sw = sw.replace(/var CACHE = 'danieloa-[^']+'/, `var CACHE = 'danieloa-${version}'`);
  sw = bumpAssetVersion(sw, version);
  if (!sw.includes('site-config.js')) {
    sw = sw.replace(
      "  '/translations.js",
      `  '/site-config.js?v=${version}',\n  '/translations.js`
    );
  }
  return sw;
}

export function runBuild({ bumpVersion = false } = {}) {
  let version = read('asset-version.txt').trim();
  if (bumpVersion) {
    const date = new Date().toISOString().slice(0, 10).replace(/-/g, '');
    let hash = 'dev';
    try {
      hash = execSync('git rev-parse --short HEAD', { cwd: ROOT }).toString().trim();
    } catch {
      /* no git */
    }
    version = `${date}-${hash}`;
    write('asset-version.txt', version + '\n');
  }

  const lastmod = new Date().toISOString().slice(0, 10);
  const faq = JSON.parse(read('content/faq.json'));
  const template = read('scripts/templates/case-study.html');
  const caseDir = join(ROOT, 'content/case-studies');
  const caseFiles = readdirSync(caseDir)
    .filter((f) => f.endsWith('.json'))
    .map((f) => JSON.parse(readFileSync(join(caseDir, f), 'utf8')));

  write('site-config.js', buildSiteConfig(version));
  write('llms.txt', buildLlmsTxt(caseFiles));
  write('sitemap.xml', buildSitemap(caseFiles, lastmod));
  write('case-i18n.js', buildCaseI18n(caseFiles));

  mkdirSync(join(ROOT, 'case-studies'), { recursive: true });
  for (const c of caseFiles) {
    write(`case-studies/${c.slug}.html`, buildCaseStudyHtml(c, template, version, lastmod));
  }

  write('index.html', patchIndexHtml(read('index.html'), faq.en, version, lastmod));
  write('translations.js', patchTranslations(read('translations.js'), faq));
  write('sw.js', buildSw(version));

  console.log(`build: ok (version ${version}, lastmod ${lastmod})`);
  return version;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  runBuild({ bumpVersion: process.argv.includes('--bump') });
}
